// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230301083101_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Entities.FIRMALAR", b =>
                {
                    b.Property<int>("firmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adresbilgisi")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("firmaadi")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("telefon")
                        .HasColumnType("Varchar(16)");

                    b.Property<string>("vergidairesi")
                        .HasColumnType("Varchar(60)");

                    b.Property<string>("vergino")
                        .HasColumnType("Varchar(40)");

                    b.HasKey("firmaID");

                    b.ToTable("FIRMALAR");
                });

            modelBuilder.Entity("EntityLayer.Entities.KULLANICILAR", b =>
                {
                    b.Property<int>("kullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("firmagirisi")
                        .HasColumnType("bit");

                    b.Property<string>("kullaniciadi")
                        .HasColumnType("Varchar(50)");

                    b.Property<bool>("kullanicipaneli")
                        .HasColumnType("bit");

                    b.Property<bool>("projeler")
                        .HasColumnType("bit");

                    b.Property<bool>("raporlar")
                        .HasColumnType("bit");

                    b.Property<bool>("rezerveacma")
                        .HasColumnType("bit");

                    b.Property<bool>("satinalma")
                        .HasColumnType("bit");

                    b.Property<string>("sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("siparisduzenleme")
                        .HasColumnType("bit");

                    b.Property<bool>("siparisgirisi")
                        .HasColumnType("bit");

                    b.Property<bool>("siparisiptali")
                        .HasColumnType("bit");

                    b.Property<bool>("stokcikisduzenleme")
                        .HasColumnType("bit");

                    b.Property<bool>("stokcikisi")
                        .HasColumnType("bit");

                    b.Property<bool>("stokdurumu")
                        .HasColumnType("bit");

                    b.Property<bool>("stokgirisduzenleme")
                        .HasColumnType("bit");

                    b.Property<bool>("stokgirisi")
                        .HasColumnType("bit");

                    b.Property<bool>("stokgirisisilme")
                        .HasColumnType("bit");

                    b.HasKey("kullaniciID");

                    b.ToTable("KULLANICILAR");
                });

            modelBuilder.Entity("EntityLayer.Entities.PROJELER", b =>
                {
                    b.Property<int>("projeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("anlasmatutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("firma")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("proje")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("projeadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projekodu")
                        .HasColumnType("int");

                    b.HasKey("projeID");

                    b.ToTable("PROJELER");
                });

            modelBuilder.Entity("EntityLayer.Entities.SIPARIS", b =>
                {
                    b.Property<int>("siparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FIRMALARfirmaID")
                        .HasColumnType("int");

                    b.Property<int?>("KULLANICILARkullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("PROJELERprojeID")
                        .HasColumnType("int");

                    b.Property<int?>("STOKKARTIstokkodu")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasColumnType("Varchar(100)");

                    b.Property<decimal>("alinanmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("durumu")
                        .HasColumnType("Varchar(20)");

                    b.Property<int>("firmaID")
                        .HasColumnType("int");

                    b.Property<decimal>("kalanmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("kullaniciID")
                        .HasColumnType("int");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("projekodu")
                        .HasColumnType("int");

                    b.Property<string>("saciklama")
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("satinalmaID")
                        .HasColumnType("int");

                    b.Property<int>("siparisFirmaID")
                        .HasColumnType("int");

                    b.Property<bool>("siparisiptal")
                        .HasColumnType("bit");

                    b.Property<decimal>("stokeklenenmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stokkodu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("taleptarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("termintarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("siparisID");

                    b.HasIndex("FIRMALARfirmaID");

                    b.HasIndex("KULLANICILARkullaniciID");

                    b.HasIndex("PROJELERprojeID");

                    b.HasIndex("STOKKARTIstokkodu");

                    b.ToTable("SIPARIS");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKCIKISI", b =>
                {
                    b.Property<int>("stokcikisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KULLANICILARkullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("PROJELERprojeID")
                        .HasColumnType("int");

                    b.Property<int?>("STOKKARTIstokkodu")
                        .HasColumnType("int");

                    b.Property<decimal>("birimfiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("kullaniciID")
                        .HasColumnType("int");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("projekodu")
                        .HasColumnType("int");

                    b.Property<int>("stokgirisID")
                        .HasColumnType("int");

                    b.Property<int?>("stokgirisID1")
                        .HasColumnType("int");

                    b.Property<int>("stokkodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("toplamtutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("stokcikisID");

                    b.HasIndex("KULLANICILARkullaniciID");

                    b.HasIndex("PROJELERprojeID");

                    b.HasIndex("STOKKARTIstokkodu");

                    b.HasIndex("stokgirisID1");

                    b.ToTable("STOKCIKISI");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKDURUMU", b =>
                {
                    b.Property<int>("stokdurumuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("STOKKARTIstokkodu")
                        .HasColumnType("int");

                    b.Property<decimal>("kullanilabilirmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ortalamabirimfiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("rezervealinmismiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stokkodu")
                        .HasColumnType("int");

                    b.Property<decimal>("toplamtutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("stokdurumuID");

                    b.HasIndex("STOKKARTIstokkodu");

                    b.ToTable("STOKDURUMU");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKGIRISI", b =>
                {
                    b.Property<int>("stokgirisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FIRMALARfirmaID")
                        .HasColumnType("int");

                    b.Property<int?>("KULLANICILARkullaniciID")
                        .HasColumnType("int");

                    b.Property<int?>("PROJELERprojeID")
                        .HasColumnType("int");

                    b.Property<int?>("STOKKARTIstokkodu")
                        .HasColumnType("int");

                    b.Property<decimal>("birimfiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("faturano")
                        .HasColumnType("Varchar(20)");

                    b.Property<DateTime>("faturatarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("firmaID")
                        .HasColumnType("int");

                    b.Property<string>("irsaliyeno")
                        .HasColumnType("Varchar(20)");

                    b.Property<DateTime>("irsaliyetarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("kdv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("kdvdahilbirimfiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("kdvtutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("kullaniciID")
                        .HasColumnType("int");

                    b.Property<decimal>("kullanilabilirmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("projekodu")
                        .HasColumnType("int");

                    b.Property<int>("siparisID")
                        .HasColumnType("int");

                    b.Property<int>("stokkodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("toplamtutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("stokgirisID");

                    b.HasIndex("FIRMALARfirmaID");

                    b.HasIndex("KULLANICILARkullaniciID");

                    b.HasIndex("PROJELERprojeID");

                    b.HasIndex("STOKKARTIstokkodu");

                    b.HasIndex("siparisID");

                    b.ToTable("STOKGIRISI");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKKARTI", b =>
                {
                    b.Property<int>("stokkodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("boy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("en")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("kalinlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("maxmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("minmiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tanim")
                        .HasColumnType("Varchar(100)");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("uretici")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("urunadi")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("yuzey")
                        .HasColumnType("Varchar(50)");

                    b.HasKey("stokkodu");

                    b.ToTable("STOKKARTI");
                });

            modelBuilder.Entity("EntityLayer.Entities.SIPARIS", b =>
                {
                    b.HasOne("EntityLayer.Entities.FIRMALAR", "FIRMALAR")
                        .WithMany("SIPARIS")
                        .HasForeignKey("FIRMALARfirmaID");

                    b.HasOne("EntityLayer.Entities.KULLANICILAR", "KULLANICILAR")
                        .WithMany("SIPARIS")
                        .HasForeignKey("KULLANICILARkullaniciID");

                    b.HasOne("EntityLayer.Entities.PROJELER", "PROJELER")
                        .WithMany("SIPARIS")
                        .HasForeignKey("PROJELERprojeID");

                    b.HasOne("EntityLayer.Entities.STOKKARTI", "STOKKARTI")
                        .WithMany("SIPARIS")
                        .HasForeignKey("STOKKARTIstokkodu");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKCIKISI", b =>
                {
                    b.HasOne("EntityLayer.Entities.KULLANICILAR", "KULLANICILAR")
                        .WithMany("STOKCIKISI")
                        .HasForeignKey("KULLANICILARkullaniciID");

                    b.HasOne("EntityLayer.Entities.PROJELER", "PROJELER")
                        .WithMany("STOKCIKISI")
                        .HasForeignKey("PROJELERprojeID");

                    b.HasOne("EntityLayer.Entities.STOKKARTI", "STOKKARTI")
                        .WithMany()
                        .HasForeignKey("STOKKARTIstokkodu");

                    b.HasOne("EntityLayer.Entities.STOKGIRISI", "STOKGIRISI")
                        .WithMany("STOKCIKISI")
                        .HasForeignKey("stokgirisID1");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKDURUMU", b =>
                {
                    b.HasOne("EntityLayer.Entities.STOKKARTI", "STOKKARTI")
                        .WithMany("STOKDURUMU")
                        .HasForeignKey("STOKKARTIstokkodu");
                });

            modelBuilder.Entity("EntityLayer.Entities.STOKGIRISI", b =>
                {
                    b.HasOne("EntityLayer.Entities.FIRMALAR", "FIRMALAR")
                        .WithMany("STOKGIRISI")
                        .HasForeignKey("FIRMALARfirmaID");

                    b.HasOne("EntityLayer.Entities.KULLANICILAR", "KULLANICILAR")
                        .WithMany("STOKGIRISI")
                        .HasForeignKey("KULLANICILARkullaniciID");

                    b.HasOne("EntityLayer.Entities.PROJELER", "PROJELER")
                        .WithMany("STOKGIRISI")
                        .HasForeignKey("PROJELERprojeID");

                    b.HasOne("EntityLayer.Entities.STOKKARTI", "STOKKARTI")
                        .WithMany("STOKGIRISI")
                        .HasForeignKey("STOKKARTIstokkodu");

                    b.HasOne("EntityLayer.Entities.SIPARIS", "SIPARIS")
                        .WithMany("STOKGIRISI")
                        .HasForeignKey("siparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
